/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.HouseController;
import Controller.UserController;
import Model.House;
import Model.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tapet
 */
public class TelaCadastroResidencia extends javax.swing.JFrame {

    HouseController houseController = new HouseController();
    UserController userController = new UserController();
    DefaultTableModel tblModel;
   
    

    /**
     * Creates new form TelaUsuário
     */
    public TelaCadastroResidencia() {

        initComponents();

      

        tblModel = (DefaultTableModel) jTHouses.getModel();
        for (House house : houseController.all()) {
            String[] rowData = {String.valueOf(house.getId()), house.getAdress(), String.valueOf(house.getNumber()), String.valueOf(house.getSize())};
            tblModel.addRow(rowData);
        }
        buttonRegProp.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxfNumberHouse = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxfStreetHouse = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        buttonRegProp = new javax.swing.JButton();
        btn_adicionar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTHouses = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        TxfSizeHouse = new javax.swing.JTextField();
        house_id = new javax.swing.JTextField();
        btn_excluir = new javax.swing.JButton();
        btn_refreshTable = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogosCondomínioMenor.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/condoInfo.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Condomínio Residencial Univasf");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(88, 88, 86));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Residências", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("ID Residência:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 30));

        TxfNumberHouse.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TxfNumberHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfNumberHouseActionPerformed(evt);
            }
        });
        jPanel3.add(TxfNumberHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 70, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Rua da unidade");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, 30));

        TxfStreetHouse.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TxfStreetHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfStreetHouseActionPerformed(evt);
            }
        });
        jPanel3.add(TxfStreetHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 310, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Inclua as informações relativas à nova residência");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        buttonRegProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userpropietario.png"))); // NOI18N
        buttonRegProp.setText("Registrar Proprietário");
        buttonRegProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegPropActionPerformed(evt);
            }
        });
        jPanel3.add(buttonRegProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 210, 50));

        btn_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adicionar_1.png"))); // NOI18N
        btn_adicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adicionarMouseClicked(evt);
            }
        });
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_adicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 50, 50));

        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 50, 50));

        jTHouses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#ID", "Endereço", "Número", "Tamanho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTHouses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTHousesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTHouses);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 1000, 190));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Tamanho da Unidade (m²)");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, 30));

        TxfSizeHouse.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TxfSizeHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfSizeHouseActionPerformed(evt);
            }
        });
        jPanel3.add(TxfSizeHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, 50, 30));

        house_id.setEditable(false);
        house_id.setEnabled(false);
        house_id.setFocusable(false);
        house_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                house_idActionPerformed(evt);
            }
        });
        jPanel3.add(house_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 70, 30));

        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jPanel3.add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 50, 50));

        btn_refreshTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remover.png"))); // NOI18N
        btn_refreshTable.setIconTextGap(3);
        btn_refreshTable.setMaximumSize(new java.awt.Dimension(25, 30));
        btn_refreshTable.setMinimumSize(new java.awt.Dimension(25, 30));
        btn_refreshTable.setPreferredSize(new java.awt.Dimension(25, 30));
        btn_refreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshTableActionPerformed(evt);
            }
        });
        jPanel3.add(btn_refreshTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 40, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Número da Unidade");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(576, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxfNumberHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfNumberHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfNumberHouseActionPerformed

    private void TxfStreetHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfStreetHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfStreetHouseActionPerformed

    private void TxfSizeHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfSizeHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfSizeHouseActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed

        String numberHouse = TxfNumberHouse.getText();
        String streetHouse = TxfStreetHouse.getText();
        String sizeHouse = TxfSizeHouse.getText();
        HouseController house = new HouseController();
        house.insert(streetHouse, Integer.parseInt(sizeHouse), Integer.parseInt(numberHouse));
        refreshTable();

    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void btn_adicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adicionarMouseClicked

    }//GEN-LAST:event_btn_adicionarMouseClicked

    private void house_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_house_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_house_idActionPerformed

    private void buttonRegPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegPropActionPerformed


    }//GEN-LAST:event_buttonRegPropActionPerformed

    private void btn_refreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshTableActionPerformed
        limparCampos();
        refreshTable();
    }//GEN-LAST:event_btn_refreshTableActionPerformed

   
    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
            try {
            int idSelected = Integer.parseInt(house_id.getText());

           
            houseController.delete(idSelected);
            refreshTable();
            limparCampos();
        } catch (NumberFormatException e) {
            // Se o texto não puder ser convertido para um número inteiro
            JOptionPane.showMessageDialog(this, "Por favor, insira um ID válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Captura de exceções genéricas
            JOptionPane.showMessageDialog(this, "Ocorreu um erro durante a exclusão do usuário.", "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void jTHousesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTHousesMouseClicked
       
        
        int selectedRow = jTHouses.getSelectedRow();
        DefaultTableModel tblModelUsers = (DefaultTableModel) jTHouses.getModel();
        
         house_id.setText(tblModelUsers.getValueAt(selectedRow, 0).toString());
        TxfStreetHouse.setText(tblModelUsers.getValueAt(selectedRow, 1).toString());
        TxfNumberHouse.setText(tblModelUsers.getValueAt(selectedRow, 2).toString());
        TxfSizeHouse.setText(tblModelUsers.getValueAt(selectedRow, 3).toString());
        
        if(house_id.getText() != ""){
            int x;
        }
      
    }//GEN-LAST:event_jTHousesMouseClicked

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
       try {
           
        String numberHouse = TxfNumberHouse.getText();
        String streetHouse = TxfStreetHouse.getText();
        String sizeHouse = TxfSizeHouse.getText(); 
        String IdHouse = house_id.getText();
        
        HouseController house = new HouseController();

           house.update(Integer.parseInt(IdHouse), streetHouse ,  Integer.parseInt(sizeHouse), Integer.parseInt(numberHouse));
           refreshTable();
            //  JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um ID válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro durante a atualização do usuário.", "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    void limparCampos() {
        TxfNumberHouse.setText("");
        TxfStreetHouse.setText("");
        TxfSizeHouse.setText("");
        house_id.setText("");
    }

    void refreshTable() {
        
        tblModel = (DefaultTableModel) jTHouses.getModel();
         tblModel.setRowCount(0);
        
        for (House house : houseController.all()) {
            String[] rowData = {String.valueOf(house.getId()), house.getAdress(), String.valueOf(house.getNumber()), String.valueOf(house.getSize())};
            tblModel.addRow(rowData);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxfNumberHouse;
    private javax.swing.JTextField TxfSizeHouse;
    private javax.swing.JTextField TxfStreetHouse;
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_refreshTable;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton buttonRegProp;
    private javax.swing.JTextField house_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTHouses;
    // End of variables declaration//GEN-END:variables
}
