/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.HouseController;
import Controller.UserController;
import Model.House;
import Model.User;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.security.util.Password;

/**
 *
 * @author tapet
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {

    UserController userController = new UserController();

    public TelaCadastroUsuario() {

        initComponents();
        TxfUserID.setEnabled(false);
        DefaultTableModel tblModelUsers = (DefaultTableModel) jTUsers.getModel();
        for (User user : userController.all()) {
            String[] rowData = {String.valueOf(user.getId()), user.getName(), String.valueOf(user.getPhone()), String.valueOf(user.getCpf()), String.valueOf(user.getUsername()), String.valueOf(user.getIs_admin())};
            tblModelUsers.addRow(rowData);
        }

        System.out.printf("\n\n\n\n %s", userController.find(11));
        //tblModelUsers.setRowCount(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxfUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxfUserUsername = new javax.swing.JTextField();
        jCBUsers = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_code_access = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_excluir = new javax.swing.JButton();
        btn_adicionar = new javax.swing.JButton();
        btn_salvarqaa = new javax.swing.JButton();
        TxfUserPassword = new javax.swing.JPasswordField();
        TxfUserID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxfUserPhone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTUsers = new javax.swing.JTable();
        TxfUserCpf = new javax.swing.JTextField();
        TxfUserSearch = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        btn_refreshTable = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogosCondomínioMenor.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/condoInfo.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Condomínio Residencial Univasf");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(88, 88, 86));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Nome:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        TxfUserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TxfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfUserNameActionPerformed(evt);
            }
        });
        jPanel3.add(TxfUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 250, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Login:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        TxfUserUsername.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TxfUserUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfUserUsernameActionPerformed(evt);
            }
        });
        jPanel3.add(TxfUserUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 250, 30));

        jCBUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar Tipo de Usuário", "Administrador", "Funcionário", "Morador" }));
        jCBUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBUsersActionPerformed(evt);
            }
        });
        jPanel3.add(jCBUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 270, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Senha:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 70, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel7.setText("Telefone:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Código de Acesso:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, 30));

        jTextField_code_access.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField_code_access.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_code_accessActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField_code_access, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 130, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Insira as informações referentes ao novo usuário");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        jPanel3.add(btn_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 50, 50));

        btn_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adicionar_1.png"))); // NOI18N
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_adicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 50, 50));

        btn_salvarqaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        btn_salvarqaa.setIconTextGap(3);
        btn_salvarqaa.setMaximumSize(new java.awt.Dimension(25, 30));
        btn_salvarqaa.setMinimumSize(new java.awt.Dimension(25, 30));
        btn_salvarqaa.setPreferredSize(new java.awt.Dimension(25, 30));
        btn_salvarqaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarqaaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_salvarqaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 40, 40));

        TxfUserPassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TxfUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfUserPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(TxfUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 230, 30));

        TxfUserID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TxfUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfUserIDActionPerformed(evt);
            }
        });
        jPanel3.add(TxfUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 250, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("ID:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("CPF:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, 30));

        TxfUserPhone.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TxfUserPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfUserPhoneActionPerformed(evt);
            }
        });
        jPanel3.add(TxfUserPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 230, 30));

        jTUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#ID", "Nome", "Username", "CPF", "Telefone", "ADM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUsersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTUsers);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1000, 230));

        TxfUserCpf.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        TxfUserCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfUserCpfActionPerformed(evt);
            }
        });
        jPanel3.add(TxfUserCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 230, 30));

        TxfUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxfUserSearchActionPerformed(evt);
            }
        });
        jPanel3.add(TxfUserSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 230, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Pesquisar:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, 30));

        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salvar.png"))); // NOI18N
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 50, 50));

        btn_refreshTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/remover.png"))); // NOI18N
        btn_refreshTable.setIconTextGap(3);
        btn_refreshTable.setMaximumSize(new java.awt.Dimension(25, 30));
        btn_refreshTable.setMinimumSize(new java.awt.Dimension(25, 30));
        btn_refreshTable.setPreferredSize(new java.awt.Dimension(25, 30));
        btn_refreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshTableActionPerformed(evt);
            }
        });
        jPanel3.add(btn_refreshTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 40, 40));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(576, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfUserNameActionPerformed

    private void TxfUserUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfUserUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfUserUsernameActionPerformed

    private void jTextField_code_accessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_code_accessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_code_accessActionPerformed

    private void TxfUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfUserIDActionPerformed

    private void TxfUserPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfUserPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfUserPhoneActionPerformed

    private void jCBUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBUsersActionPerformed

    boolean checkTipoUser() {
        String tipoUser = (String) jCBUsers.getSelectedItem();
        return tipoUser.equals("Administrador");
    }

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed

        String nomeUser = TxfUserName.getText();
        String telefoneUser = TxfUserPhone.getText();
        String usernameUser = TxfUserUsername.getText();
        String cpfUser = TxfUserCpf.getText();

        if (nomeUser.isEmpty() || telefoneUser.isEmpty() || usernameUser.isEmpty() || cpfUser.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            userController.insert(nomeUser, telefoneUser, cpfUser, usernameUser, "asd", checkTipoUser());
            refreshTable();
        }

    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void TxfUserCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfUserCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfUserCpfActionPerformed

    private void jTUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsersMouseClicked

        int selectedRow = jTUsers.getSelectedRow();
        DefaultTableModel tblModelUsers = (DefaultTableModel) jTUsers.getModel();
        TxfUserID.setText(tblModelUsers.getValueAt(selectedRow, 0).toString());
        TxfUserName.setText(tblModelUsers.getValueAt(selectedRow, 1).toString());
        TxfUserUsername.setText(tblModelUsers.getValueAt(selectedRow, 2).toString());
        TxfUserCpf.setText(tblModelUsers.getValueAt(selectedRow, 3).toString());
        TxfUserPhone.setText(tblModelUsers.getValueAt(selectedRow, 4).toString());
        // TxfUserID.setText(tblModelUsers.getValueAt(selectedRow, 1).toString());


    }//GEN-LAST:event_jTUsersMouseClicked

    private void TxfUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfUserPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxfUserPasswordActionPerformed

    private void TxfUserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxfUserSearchActionPerformed


    }//GEN-LAST:event_TxfUserSearchActionPerformed

    private void btn_salvarqaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarqaaActionPerformed
        DefaultTableModel tblModelUsers = (DefaultTableModel) jTUsers.getModel();
        String termoBusca = TxfUserSearch.getText().toLowerCase();
        tblModelUsers.setRowCount(0);
        for (User user : userController.all()) {
            if (user.getName().toLowerCase().contains(termoBusca)) {
                String[] rowData = {String.valueOf(user.getId()), user.getName(), String.valueOf(user.getUsername()), String.valueOf(user.getCpf()), String.valueOf(user.getPhone()), String.valueOf(user.getIs_admin())};
                tblModelUsers.addRow(rowData);
            }
        }

    }//GEN-LAST:event_btn_salvarqaaActionPerformed

    private void btn_refreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshTableActionPerformed
        limparCampos();
        refreshTable();

    }//GEN-LAST:event_btn_refreshTableActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        try {
            int idSelected = Integer.parseInt(TxfUserID.getText());

            userController.delete(idSelected);

            refreshTable();
        } catch (NumberFormatException e) {
            // Se o texto não puder ser convertido para um número inteiro
            JOptionPane.showMessageDialog(this, "Por favor, insira um ID válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Captura de exceções genéricas
            JOptionPane.showMessageDialog(this, "Ocorreu um erro durante a exclusão do usuário.", "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed

        try {
            String nomeUser = TxfUserName.getText();
            String telefoneUser = TxfUserPhone.getText();
            String usernameUser = TxfUserUsername.getText();
            String cpfUser = TxfUserCpf.getText();
            int idSelected = Integer.parseInt(TxfUserID.getText());

            userController.update(idSelected, nomeUser, telefoneUser, cpfUser, usernameUser, "asd", checkTipoUser());

            //  JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um ID válido.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro durante a atualização do usuário.", "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    void refreshTable() {
        DefaultTableModel tblModelUsers = (DefaultTableModel) jTUsers.getModel();
        tblModelUsers.setRowCount(0);
        for (User user : userController.all()) {
            String[] rowData = {String.valueOf(user.getId()), user.getName(), String.valueOf(user.getUsername()), String.valueOf(user.getCpf()), String.valueOf(user.getPhone()), String.valueOf(user.getIs_admin())};
            tblModelUsers.addRow(rowData);
        }
    }

    private void limparCampos() {
        TxfUserName.setText("");
        TxfUserPhone.setText("");
        TxfUserUsername.setText("");
        TxfUserCpf.setText("");
        TxfUserID.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxfUserCpf;
    private javax.swing.JTextField TxfUserID;
    private javax.swing.JTextField TxfUserName;
    private javax.swing.JPasswordField TxfUserPassword;
    private javax.swing.JTextField TxfUserPhone;
    private javax.swing.JTextField TxfUserSearch;
    private javax.swing.JTextField TxfUserUsername;
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_refreshTable;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_salvarqaa;
    private javax.swing.JComboBox<String> jCBUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTUsers;
    private javax.swing.JTextField jTextField_code_access;
    // End of variables declaration//GEN-END:variables
}
